In [2]:
import pandas as pd
import numpy as np


In [3]:
df1 = pd.read_csv("/content/dataset_carprices.csv")

In [5]:
df = pd.read_csv('/content/df1.csv')


In [6]:
df


index                                Car Name  KMs Driven Fuel Type  \
0         0  Jeep Compass 2.0 Longitude Option BSIV       86226    Diesel   
1         1            Renault Duster RXZ Turbo CVT       86226    Petrol   
2         2                      Toyota Camry 2.5 G       86226    Petrol   
3         3                       Honda Jazz VX CVT       26696    Petrol   
4         4        Volkswagen Polo 1.2 MPI Highline       69414    Petrol   
...     ...                                     ...         ...       ...   
5507   5507                 BMW X1 sDrive 20d xLine       45000    Diesel   
5508   5508                   BMW M Series M4 Coupe       29000    Petrol   
5509   5509              Jaguar XF 2.2 Litre Luxury       90000    Diesel   
5510   5510                      BMW 7 Series 730Ld       79000    Diesel   
5511   5511               BMW 5 Series 520d M Sport       42000    Diesel   

     Transmission  Ownership  Manufacture  Engine  Seats  carprice  \
0          Manual          1         2017    1956      5     10.03   
1       Automatic          1         2021    1330      5     12.83   
2       Automatic          1         2016    2494      5     16.40   
3       Automatic          1         2018    1199      5      7.77   
4          Manual          1         2016    1199      5      5.15   
...           ...        ...          ...     ...    ...       ...   
5507    Automatic          1         2018    2995      7     28.90   
5508    Automatic          2         2015    1968      5     64.90   
5509    Automatic          2         2013    2755      5     13.75   
5510    Automatic          3         2015    2967      6     29.90   
5511    Automatic          2         2017    1991      5     31.90   

      CarPrices in Lakhs  
0                  10.03  
1                  12.83  
2                  16.40  
3                   7.77  
4                   5.15  
...                  ...  
5507               28.90  
5508               64.90  
5509               13.75  
5510               29.90  
5511               31.90  

[5512 rows x 11 columns]

In [ ]:
df.iloc[0,:3]

index                                              0
Car Name      Jeep Compass 2.0 Longitude Option BSIV
KMs Driven                                     86226
Name: 0, dtype: object

In [ ]:
df.iloc[:,2]

0       86226
1       86226
2       86226
3       26696
4       69414
        ...  
5507    45000
5508    29000
5509    90000
5510    79000
5511    42000
Name: KMs Driven, Length: 5512, dtype: int64

In [ ]:
df[['Ownership','Manufacture']].value_counts()

In [ ]:
df[df['Manufacture']==2021]['Fuel Type'].value_counts()

Petrol      230
Diesel      104
Cng           7
Electric      3
Name: Fuel Type, dtype: int64

In [ ]:
df['Car Name'].value_counts()

Maruti Alto 800 LXI          53
Maruti Swift VXI             46
Maruti Wagon R VXI BS IV     43
Maruti Swift Dzire VDI       42
Maruti Swift Dzire VXI       42
                             ..
Tata New Safari XT            1
Hyundai Creta 1.6 E Plus      1
Toyota Etios 2014-2016 GD     1
Mahindra Marazzo M8 8Str      1
BMW M Series M4 Coupe         1
Name: Car Name, Length: 1896, dtype: int64

In [ ]:
len(df['Car Name'].unique())

1896

In [ ]:
df.shape

(5512, 10)

In [ ]:
df.shape


(5512, 10)

In [ ]:
df[df['KMs Driven']>=90000].value_counts()

index  Car Name                            KMs Driven  Fuel Type  Transmission  Ownership  Manufacture  Engine  Seats  CarPrices in Lakhs
11     Honda City i VTEC CVT SV            110284      Petrol     Automatic     1          2014         1497    5      5.43                  1
3863   Renault KWID RXT                    110000      Petrol     Manual        2          2016         1461    5      1.91                  1
3884   Honda Amaze E i-DTEC                110000      Diesel     Manual        1          2017         796     5      3.50                  1
3882   Tata Indica DLS BSIII               120000      Diesel     Manual        3          2010         1197    5      1.00                  1
3881   Maruti Swift ZDi                    120000      Diesel     Manual        1          2014         1461    5      3.79                  1
                                                                                                                                            ..
2277

In [ ]:
df.describe()

index     KMs Driven    Ownership  Manufacture       Engine  \
count  5512.000000    5512.000000  5512.000000  5512.000000  5512.000000   
mean   2755.500000   63229.823657     1.421807  2015.455552  1532.299710   
std    1591.321673   41840.993417     0.703092     3.927974   579.210876   
min       0.000000     250.000000     0.000000  1995.000000     0.000000   
25%    1377.750000   33188.000000     1.000000  2013.000000  1197.000000   
50%    2755.500000   59013.000000     1.000000  2016.000000  1396.000000   
75%    4133.250000   84281.000000     2.000000  2018.000000  1950.000000   
max    5511.000000  560000.000000     5.000000  2022.000000  5950.000000   

             Seats  CarPrices in Lakhs  
count  5512.000000         5512.000000  
mean      5.250726         1700.984784  
std       0.720075        11471.329530  
min       2.000000            1.000000  
25%       5.000000            3.250000  
50%       5.000000            5.640000  
75%       5.000000           10.892500  
max       8.000000        99999.000000

In [ ]:
CompanyName = df['Car Name'].apply(lambda x : x.split(' ')[0])
CompanyName

0             Jeep
1          Renault
2           Toyota
3            Honda
4       Volkswagen
           ...    
5507           BMW
5508           BMW
5509        Jaguar
5510           BMW
5511           BMW
Name: Car Name, Length: 5512, dtype: object

In [ ]:
df['comapnyname']=CompanyName.tolist()

index                                Car Name  KMs Driven Fuel Type  \
0         0  Jeep Compass 2.0 Longitude Option BSIV       86226    Diesel   
1         1            Renault Duster RXZ Turbo CVT       86226    Petrol   
2         2                      Toyota Camry 2.5 G       86226    Petrol   
3         3                       Honda Jazz VX CVT       26696    Petrol   
4         4        Volkswagen Polo 1.2 MPI Highline       69414    Petrol   
...     ...                                     ...         ...       ...   
5507   5507                 BMW X1 sDrive 20d xLine       45000    Diesel   
5508   5508                   BMW M Series M4 Coupe       29000    Petrol   
5509   5509              Jaguar XF 2.2 Litre Luxury       90000    Diesel   
5510   5510                      BMW 7 Series 730Ld       79000    Diesel   
5511   5511               BMW 5 Series 520d M Sport       42000    Diesel   

     Transmission  Ownership  Manufacture  Engine  Seats  CarPrices in Lakhs  \
0          Manual          1         2017    1956      5               10.03   
1       Automatic          1         2021    1330      5               12.83   
2       Automatic          1         2016    2494      5               16.40   
3       Automatic          1         2018    1199      5                7.77   
4          Manual          1         2016    1199      5                5.15   
...           ...        ...          ...     ...    ...                 ...   
5507    Automatic          1         2018    2995      7               28.90   
5508    Automatic          2         2015    1968      5               64.90   
5509    Automatic          2         2013    2755      5               13.75   
5510    Automatic          3         2015    2967      6               29.90   
5511    Automatic          2         2017    1991      5               31.90   

     comapnyname  
0           Jeep  
1        Renault  
2         Toyota  
3          Honda  
4     Volkswagen  
...          ...  
5507         BMW  
5508         BMW  
5509      Jaguar  
5510         BMW  
5511         BMW  

[5512 rows x 11 columns]

In [ ]:
new_cols=['comapnyname','Fuel Type','KMs Driven','Transmission','Ownership','Manufacture','Engine','Seats','CarPrices in Lakhs']
df=df.reindex(columns=new_cols)



In [ ]:
len(df['comapnyname'].unique())

32

In [ ]:
df2['Company'].unique()

array(['Jeep', 'Renault', 'Toyota', 'Honda', 'Volkswagen', 'Maruti',
       'Mahindra', 'Hyundai', 'Nissan', 'Kia', 'MG', 'Tata', 'BMW',
       'Mercedes-Benz', 'Datsun', 'Volvo', 'Audi', 'Porsche', 'Ford',
       'Chevrolet', 'Skoda', 'Lexus', 'Land', 'Mini', 'Jaguar',
       'Mitsubishi', 'Force', 'Premier', 'Fiat', 'Maserati', 'Bentley',
       'Isuzu'], dtype=object)

In [ ]:
df2=df

In [ ]:
import matplotlib as plt
import seaborn as sns

In [ ]:
x=df2.iloc[:,:8]
y=df2.iloc[:,-1]

In [ ]:
x2


array(<5512x44 sparse matrix of type '<class 'numpy.float64'>'
	with 44077 stored elements in Compressed Sparse Row format>, dtype=object)

In [ ]:
y=df1.iloc[:,-1]

In [ ]:
y

0       10.03
1       12.83
2       16.40
3        7.77
4        5.15
        ...  
5507    28.90
5508    64.90
5509    13.75
5510    29.90
5511    31.90
Name: CarPrices in Lakhs, Length: 5512, dtype: float64

In [ ]:
df2['Fuel Type'].unique()

array(['Diesel', 'Petrol', 'Cng', 'Electric', 'Lpg'], dtype=object)

In [ ]:
x2=x
x1=x

In [ ]:
x2[3][7]

In [ ]:
with np.printoptions(threshold=np.inf):
    print(x2)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x2 = np.array(ct.fit_transform(x2)) 

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
x2 = np.array(ct.fit_transform(x2)) 

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')
x2 = np.array(ct.fit_transform(x2))

In [ ]:
x1=x2

In [ ]:
x1

comapnyname Fuel Type  KMs Driven Transmission  Ownership  Manufacture  \
0           Jeep    Diesel       86226       Manual          1         2017   
1        Renault    Petrol       86226    Automatic          1         2021   
2         Toyota    Petrol       86226    Automatic          1         2016   
3          Honda    Petrol       26696    Automatic          1         2018   
4     Volkswagen    Petrol       69414       Manual          1         2016   
...          ...       ...         ...          ...        ...          ...   
5507         BMW    Diesel       45000    Automatic          1         2018   
5508         BMW    Petrol       29000    Automatic          2         2015   
5509      Jaguar    Diesel       90000    Automatic          2         2013   
5510         BMW    Diesel       79000    Automatic          3         2015   
5511         BMW    Diesel       42000    Automatic          2         2017   

      Engine  Seats  
0       1956      5  
1       1330      5  
2       2494      5  
3       1199      5  
4       1199      5  
...      ...    ...  
5507    2995      7  
5508    1968      5  
5509    2755      5  
5510    2967      6  
5511    1991      5  

[5512 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc= OneHotEncoder()
enc_data=pd.DataFrame(enc.fit_transform(x1[['comapnyname','Fuel Type','Transmission']]).toarray())

In [ ]:
enc_data

In [ ]:
New_df=x1.join(enc_data)
New_df

comapnyname Fuel Type  KMs Driven Transmission  Ownership  Manufacture  \
0           Jeep    Diesel       86226       Manual          1         2017   
1        Renault    Petrol       86226    Automatic          1         2021   
2         Toyota    Petrol       86226    Automatic          1         2016   
3          Honda    Petrol       26696    Automatic          1         2018   
4     Volkswagen    Petrol       69414       Manual          1         2016   
...          ...       ...         ...          ...        ...          ...   
5507         BMW    Diesel       45000    Automatic          1         2018   
5508         BMW    Petrol       29000    Automatic          2         2015   
5509      Jaguar    Diesel       90000    Automatic          2         2013   
5510         BMW    Diesel       79000    Automatic          3         2015   
5511         BMW    Diesel       42000    Automatic          2         2017   

      Engine  Seats    0    1  ...   29   30   31   32   33   34   35   36  \
0       1956      5  0.0  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
1       1330      5  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2       2494      5  0.0  0.0  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
3       1199      5  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
4       1199      5  0.0  0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
...      ...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
5507    2995      7  0.0  1.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
5508    1968      5  0.0  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
5509    2755      5  0.0  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
5510    2967      6  0.0  1.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
5511    1991      5  0.0  1.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   

       37   38  
0     0.0  1.0  
1     1.0  0.0  
2     1.0  0.0  
3     1.0  0.0  
4     0.0  1.0  
...   ...  ...  
5507  1.0  0.0  
5508  1.0  0.0  
5509  1.0  0.0  
5510  1.0  0.0  
5511  1.0  0.0  

[5512 rows x 47 columns]

In [ ]:
from google.colab import files

New_df.to_csv('df.csv')
files.download('df.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df= pd.read_csv('/content/df.csv')

In [ ]:
df

Unnamed: 0 comapnyname Fuel Type  KMs Driven Transmission  Ownership  \
0              0        Jeep    Diesel       86226       Manual          1   
1              1     Renault    Petrol       86226    Automatic          1   
2              2      Toyota    Petrol       86226    Automatic          1   
3              3       Honda    Petrol       26696    Automatic          1   
4              4  Volkswagen    Petrol       69414       Manual          1   
...          ...         ...       ...         ...          ...        ...   
5507        5507         BMW    Diesel       45000    Automatic          1   
5508        5508         BMW    Petrol       29000    Automatic          2   
5509        5509      Jaguar    Diesel       90000    Automatic          2   
5510        5510         BMW    Diesel       79000    Automatic          3   
5511        5511         BMW    Diesel       42000    Automatic          2   

      Manufacture  Engine  Seats    0  ...   29   30   31   32   33   34   35  \
0            2017    1956      5  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
1            2021    1330      5  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2            2016    2494      5  0.0  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3            2018    1199      5  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4            2016    1199      5  0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
...           ...     ...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
5507         2018    2995      7  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
5508         2015    1968      5  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
5509         2013    2755      5  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
5510         2015    2967      6  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
5511         2017    1991      5  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0   

       36   37   38  
0     0.0  0.0  1.0  
1     1.0  1.0  0.0  
2     1.0  1.0  0.0  
3     1.0  1.0  0.0  
4     1.0  0.0  1.0  
...   ...  ...  ...  
5507  0.0  1.0  0.0  
5508  1.0  1.0  0.0  
5509  0.0  1.0  0.0  
5510  0.0  1.0  0.0  
5511  0.0  1.0  0.0  

[5512 rows x 48 columns]

In [ ]:
df.drop(['Unnamed: 0'], axis=1,inplace=True)

In [ ]:
y= df1.iloc[:,-1]
y

0       10.03
1       12.83
2       16.40
3        7.77
4        5.15
        ...  
5507    28.90
5508    64.90
5509    13.75
5510    29.90
5511    31.90
Name: CarPrices in Lakhs, Length: 5512, dtype: float64

In [ ]:
df


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size = 0.2, random_state = 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train.iloc[:, :5] = sc.fit_transform(X_train.iloc[:, :5])
X_test.iloc[:, :5] = sc.transform(X_test.iloc[:, :5])


In [ ]:
X_train

In [ ]:
y_test= y_test.to_numpy()

In [ ]:
y_train = y_train.reshape(len(y_train),1)
y_train

In [ ]:
y_test = y_test.reshape(len(y_test),1)
y_test

In [ ]:
y_train = sc.fit_transform(y_train)
y_test = sc.transform(y_test)

In [ ]:
y_train

array([[-0.14796551],
       [-0.14814775],
       [-0.1480657 ],
       ...,
       [-0.14815898],
       [-0.14758635],
       [-0.14783941]])

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[-0.15 -0.15]
 [-0.15 -0.15]
 [-0.15 -0.15]
 ...
 [-0.15 -0.15]
 [-0.15 -0.15]
 [-0.15 -0.15]]


In [ ]:
y_pred = y_pred.reshape(len(y_pred),1)
y_pred

array([[-0.15],
       [-0.15],
       [-0.15],
       ...,
       [-0.15],
       [-0.15],
       [-0.15]])

In [ ]:
y_pred2 = sc.inverse_transform(y_pred)
y_pred2

In [ ]:
y_test2= sc.inverse_transform(y_test)

In [ ]:
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1))

[[ 4.71  4.71]
 [13.5   9.06]
 [ 6.9   7.92]
 ...
 [ 5.19  4.26]
 [29.75 29.75]
 [16.75 18.28]]


In [ ]:
my_arr=np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test2.reshape(len(y_test2),1)),1)

In [ ]:
import sys
with np.printoptions(threshold=sys.maxsize):
    print(my_arr)